[tool.poetry]
name = "terrarium-sensor"
version = "0.1.0"
description = ""
authors = ["Torai Lin <torailin55@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
